In [156]:
import pandas as pd
import numpy as np
import scipy.io

In [238]:
data = pd.read_csv('X_train.csv')

In [240]:
data

weeks  flu  swine  stomach  symptoms  virus  bug  strep  season  \
0          0  0.0    1.0      1.0       1.0    1.0  1.0    1.0     1.0   
1          1  2.0    2.0      2.0       2.0    2.0  2.0    2.0     2.0   
2          2  0.0    1.0      1.0       1.0    1.0  1.0    1.0     1.0   
3          3  0.0    1.0      1.0       1.0    1.0  1.0    1.0     1.0   
4          4  0.0    1.0      1.0       1.0    1.0  1.0    1.0     1.0   
...      ...  ...    ...      ...       ...    ...  ...    ...     ...   
52555   1090  0.0    0.0      0.0       1.0    1.0  1.0    1.0     1.0   
52556   1091  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0   
52557   1092  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0   
52558   1093  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0   
52559   1094  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0   

       influenza  ...  tests  thinks  ankle  work  hand  complications  \
0            1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
1            2.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
2            1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
3            1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
4            1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
...          ...  ...    ...     ...    ...   ...   ...            ...   
52555        1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
52556        0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
52557        0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
52558        0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   
52559        0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0   

       children  start  aja       state  
0           0.0    0.0  0.0  new mexico  
1           0.0    0.0  0.0  new mexico  
2           0.0    0.0  0.0  new mexico  
3           0.0    0.0  0.0  new mexico  
4           0.0    0.0  0.0  new mexico  
...         ...    ...  ...         ...  
52555       0.0    0.0  0.0     wyoming  
52556       0.0    0.0  0.0     wyoming  
52557       0.0    0.0  0.0     wyoming  
52558       0.0    0.0  0.0     wyoming  
52559       0.0    0.0  0.0     wyoming  

[52560 rows x 527 columns]

In [239]:
data.shape

(52560, 527)

In [252]:

data = scipy.io.loadmat('influenza_outbreak_dataset.mat')

data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Mar 13 11:56:00 2020',
 '__version__': '1.0',
 '__globals__': [],
 'flu_X_tr': array([[<1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 3573 stored elements in Compressed Sparse Column format>,
         <1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 38755 stored elements in Compressed Sparse Column format>,
         <1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 39884 stored elements in Compressed Sparse Column format>,
         <1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 24440 stored elements in Compressed Sparse Column format>,
         <1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 40711 stored elements in Compressed Sparse Column format>,
         <1095x545 sparse matrix of type '<class 'numpy.float64'>'
         	with 38987 stored elements in Compressed Sparse Column format>,
    

In [180]:
print(data['flu_X_tr'][0][0].toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [253]:
df = pd.DataFrame()
keywords = data["flu_keywords"]

In [254]:
keys = []
for item in keywords :
    for i in item:
        keys.append(i[0])
        
keys        

['flu',
 'swine',
 'stomach',
 'symptoms',
 'virus',
 'bug',
 'strep',
 'season',
 'influenza',
 'fever',
 'thera',
 'poisoning',
 'pneumonia',
 'bird',
 'infection',
 'epidemic',
 'week',
 'bronchitis',
 'sucks',
 'immune',
 'soon',
 'colds',
 'caught',
 'medicine',
 'soup',
 'weekend',
 'dying',
 'recovering',
 'weeks',
 'meds',
 'sick',
 'outbreak',
 'cough',
 'sickness',
 'strain',
 'jab',
 'kicking',
 'catch',
 'catching',
 'bed',
 'contagious',
 'days',
 'aches',
 'yesterday',
 'battling',
 'cure',
 'coming',
 'doctor',
 'rest',
 'worst',
 'tomorrow',
 'case',
 'illness',
 'hours',
 'due',
 'worse',
 'system',
 'ini',
 'weight',
 'sinus',
 'body',
 'germs',
 'morning',
 'hangover',
 'death',
 'awful',
 'hospital',
 'fighting',
 '12s',
 'away',
 'feeling',
 'sakit',
 'horrible',
 'miserable',
 'since',
 'ebola',
 'lagi',
 'die',
 'chills',
 'finals',
 'vaccination',
 'pounds',
 'weather',
 'nasty',
 'played',
 'hour',
 'healthy',
 'sicker',
 'winter',
 'finally',
 'plague',
 'spre

In [214]:
len(keys)

525

In [255]:
locations = data["flu_locs"][0]
locations

array([array(['wyoming'], dtype='<U7'), array(['colorado'], dtype='<U8'),
       array(['nebraska'], dtype='<U8'),
       array(['washington'], dtype='<U10'),
       array(['rhode island'], dtype='<U12'),
       array(['tennessee'], dtype='<U9'),
       array(['wisconsin'], dtype='<U9'), array(['nevada'], dtype='<U6'),
       array(['maine'], dtype='<U5'),
       array(['north dakota'], dtype='<U12'),
       array(['mississippi'], dtype='<U11'),
       array(['new jersey'], dtype='<U10'),
       array(['oklahoma'], dtype='<U8'), array(['delaware'], dtype='<U8'),
       array(['minnesota'], dtype='<U9'),
       array(['north carolina'], dtype='<U14'),
       array(['illinois'], dtype='<U8'), array(['new york'], dtype='<U8'),
       array(['arkansas'], dtype='<U8'), array(['indiana'], dtype='<U7'),
       array(['maryland'], dtype='<U8'),
       array(['louisiana'], dtype='<U9'), array(['idaho'], dtype='<U5'),
       array(['arizona'], dtype='<U7'), array(['iowa'], dtype='<U4'),
       a

In [230]:
locs = []
for item in locations :
    for i in item:
        locs.append(i)
        
locs        

['wyoming',
 'colorado',
 'nebraska',
 'washington',
 'rhode island',
 'tennessee',
 'wisconsin',
 'nevada',
 'maine',
 'north dakota',
 'mississippi',
 'new jersey',
 'oklahoma',
 'delaware',
 'minnesota',
 'north carolina',
 'illinois',
 'new york',
 'arkansas',
 'indiana',
 'maryland',
 'louisiana',
 'idaho',
 'arizona',
 'iowa',
 'west virginia',
 'michigan',
 'kansas',
 'utah',
 'virginia',
 'oregon',
 'connecticut',
 'california',
 'massachusetts',
 'alaska',
 'vermont',
 'georgia',
 'pennsylvania',
 'florida',
 'hawaii',
 'district of columbia',
 'new hampshire',
 'texas',
 'missouri',
 'south carolina',
 'ohio',
 'alabama',
 'new mexico']

In [215]:
data[0]

KeyError: 0

In [233]:
Mtx = []
nums = 0
for item in data['flu_X_tr'][0]:
    print(item.shape)
    matrix = item.toarray()

    # Assuming the matrix is stored in the variable 'matrix'
    # Convert the matrix to a numpy array
    matrix_array = np.array(matrix)

    # Create a DataFrame from the numpy array
    temp = pd.DataFrame(matrix_array)
    temp = temp.iloc[ :, 0 : 525]
    temp['state'] = locs[nums]

    # Print the resulting DataFrame
    import pandas as pd

    # Assuming df1 and df2 are the DataFrames you want to concatenate
    df = pd.concat([df, temp], axis=0)
    nums = nums + 1

(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)
(1095, 545)


In [237]:
df

0    1    2    3    4    5    6    7    8    9  ...  516  517  518  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1090  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0   
1091  1.0  1.0  1.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  ...  0.0  0.0  0.0   
1092  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1093  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0  0.0   
1094  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      519  520  521  522  523  524       state  
0     0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
1     0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
2     0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
3     0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
4     0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
...   ...  ...  ...  ...  ...  ...         ...  
1090  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
1091  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
1092  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
1093  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
1094  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  

[52560 rows x 526 columns]

In [259]:
dict = {}
for i in range(0,len(keys)) :
    dict[i] = keys[i]
    
    

In [243]:
dict

{0: 'flu',
 1: 'swine',
 2: 'stomach',
 3: 'symptoms',
 4: 'virus',
 5: 'bug',
 6: 'strep',
 7: 'season',
 8: 'influenza',
 9: 'fever',
 10: 'thera',
 11: 'poisoning',
 12: 'pneumonia',
 13: 'bird',
 14: 'infection',
 15: 'epidemic',
 16: 'week',
 17: 'bronchitis',
 18: 'sucks',
 19: 'immune',
 20: 'soon',
 21: 'colds',
 22: 'caught',
 23: 'medicine',
 24: 'soup',
 25: 'weekend',
 26: 'dying',
 27: 'recovering',
 28: 'weeks',
 29: 'meds',
 30: 'sick',
 31: 'outbreak',
 32: 'cough',
 33: 'sickness',
 34: 'strain',
 35: 'jab',
 36: 'kicking',
 37: 'catch',
 38: 'catching',
 39: 'bed',
 40: 'contagious',
 41: 'days',
 42: 'aches',
 43: 'yesterday',
 44: 'battling',
 45: 'cure',
 46: 'coming',
 47: 'doctor',
 48: 'rest',
 49: 'worst',
 50: 'tomorrow',
 51: 'case',
 52: 'illness',
 53: 'hours',
 54: 'due',
 55: 'worse',
 56: 'system',
 57: 'ini',
 58: 'weight',
 59: 'sinus',
 60: 'body',
 61: 'germs',
 62: 'morning',
 63: 'hangover',
 64: 'death',
 65: 'awful',
 66: 'hospital',
 67: 'fighti

In [248]:
#rename columns 
df.rename(columns=dict,inplace=True)

In [249]:
df

flu  swine  stomach  symptoms  virus  bug  strep  season  influenza  \
0     0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
1     0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
2     0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
3     0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
4     0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
...   ...    ...      ...       ...    ...  ...    ...     ...        ...   
1090  1.0    1.0      1.0       1.0    1.0  1.0    1.0     1.0        1.0   
1091  1.0    1.0      1.0       2.0    2.0  2.0    2.0     2.0        2.0   
1092  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
1093  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        1.0   
1094  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   

      fever  ...  tests  thinks  ankle  work  hand  complications  children  \
0       1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1       0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
2       0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
3       0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
4       0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
...     ...  ...    ...     ...    ...   ...   ...            ...       ...   
1090    1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1091    2.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1092    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1093    1.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1094    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   

      start  aja       state  
0       0.0  0.0     wyoming  
1       0.0  0.0     wyoming  
2       0.0  0.0     wyoming  
3       0.0  0.0     wyoming  
4       0.0  0.0     wyoming  
...     ...  ...         ...  
1090    0.0  0.0  new mexico  
1091    0.0  0.0  new mexico  
1092    0.0  0.0  new mexico  
1093    0.0  0.0  new mexico  
1094    0.0  0.0  new mexico  

[52560 rows x 526 columns]

<h1> 


Cleaning test 




</h1>

In [250]:
df.to_csv('X_train_self.csv')

In [ ]:
data['']

In [257]:
Mtx = []
nums = 0
for item in data['flu_X_te'][0]:
    print(item.shape)
    matrix = item.toarray()

    # Assuming the matrix is stored in the variable 'matrix'
    # Convert the matrix to a numpy array
    matrix_array = np.array(matrix)

    # Create a DataFrame from the numpy array
    temp = pd.DataFrame(matrix_array)
    temp = temp.iloc[ :, 0 : 525]
    temp['state'] = locs[nums]

    # Print the resulting DataFrame
    import pandas as pd

    # Assuming df1 and df2 are the DataFrames you want to concatenate
    df = pd.concat([df, temp], axis=0)
    nums = nums + 1

(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)
(485, 545)


In [258]:
df

0    1    2    3    4    5    6    7    8    9  ...  516  517  518  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
480  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
481  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
482  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
483  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
484  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     519  520  521  522  523  524       state  
0    0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
1    0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
2    0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
3    0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
4    0.0  0.0  0.0  0.0  0.0  0.0     wyoming  
..   ...  ...  ...  ...  ...  ...         ...  
480  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
481  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
482  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
483  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  
484  0.0  0.0  0.0  0.0  0.0  0.0  new mexico  

[23280 rows x 526 columns]

In [260]:
#rename columns 
df.rename(columns=dict,inplace=True)

In [261]:
df

flu  swine  stomach  symptoms  virus  bug  strep  season  influenza  \
0    0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
1    0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
2    0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
3    0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
4    0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
..   ...    ...      ...       ...    ...  ...    ...     ...        ...   
480  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
481  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
482  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
483  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   
484  0.0    0.0      0.0       0.0    0.0  0.0    0.0     0.0        0.0   

     fever  ...  tests  thinks  ankle  work  hand  complications  children  \
0      0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
1      0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
2      0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
3      0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
4      0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
..     ...  ...    ...     ...    ...   ...   ...            ...       ...   
480    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
481    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
482    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
483    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   
484    0.0  ...    0.0     0.0    0.0   0.0   0.0            0.0       0.0   

     start  aja       state  
0      0.0  0.0     wyoming  
1      0.0  0.0     wyoming  
2      0.0  0.0     wyoming  
3      0.0  0.0     wyoming  
4      0.0  0.0     wyoming  
..     ...  ...         ...  
480    0.0  0.0  new mexico  
481    0.0  0.0  new mexico  
482    0.0  0.0  new mexico  
483    0.0  0.0  new mexico  
484    0.0  0.0  new mexico  

[23280 rows x 526 columns]

In [262]:
df.to_csv('X_test_self.csv')

<h1> 


Cleaning y




</h1>

In [264]:
y_train = data['flu_Y_tr'][0]

In [265]:
y_train

array([array([[0],
              [0],
              [0],
              ...,
              [0],
              [0],
              [0]], dtype=uint8), array([[0],
                                         [0],
                                         [0],
                                         ...,
                                         [1],
                                         [1],
                                         [1]], dtype=uint8),
       array([[0],
              [0],
              [0],
              ...,
              [0],
              [0],
              [0]], dtype=uint8), array([[0],
                                         [0],
                                         [0],
                                         ...,
                                         [0],
                                         [0],
                                         [0]], dtype=uint8),
       array([[0],
              [0],
              [0],
              ...,
              [0],
   

In [269]:
df = pd.DataFrame()

In [277]:
for item in y_train :
    array = np.array(item)

    # Create a DataFrame from the numpy array
    temp = pd.DataFrame(array)
    df = pd.concat([df, temp], axis=0)

In [278]:
df

0
0     0
1     0
2     0
3     0
4     0
...  ..
1090  1
1091  1
1092  1
1093  1
1094  1

[52560 rows x 1 columns]

In [279]:
df.to_csv('y_train_self.csv')

fixing y_test

In [284]:
y_test = data['flu_Y_te'][0]

In [285]:
df_test = pd.DataFrame()

In [286]:
for item in y_test:
    array = np.array(item)

    # Create a DataFrame from the numpy array
    temp = pd.DataFrame(array)
    df_test = pd.concat([df_test, temp], axis=0)

In [287]:
df_test

0
0    0
1    0
2    0
3    0
4    0
..  ..
480  0
481  0
482  0
483  0
484  0

[23280 rows x 1 columns]

In [288]:
df_test.to_csv('y_test_self.csv')